package org.assimbly.gateway.domain.enumeration;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ComponentType enumeration.
 * This is an alpabetic list based on Camel's component reference https://camel.apache.org/components/latest
 */
public enum ComponentType {

    ACTIVEMQ("ACTIVEMQ"),

    AHC("AHC"),

    @JsonProperty("AHC-WS")
    AHCWS("AHC-WS"),

    @JsonProperty("AHC-WSS")

    AHCWSS("AHC-WSS"),

    AMAZONMQ("AMAZONMQ"),

    AMQP("AMQP"),

    AMQPS("AMQPS"),

    APNS("APNS"),

    ARANGODB("ARANGODB"),

    AS2("AS2"),

    ASTERISK("ASTERISK"),

    ATMOS("ATMOS"),

    @JsonProperty("ATMOSPHERE-WEBSOCKET")
    ATMOSPHEREWEBSOCKET("ATMOSPHERE-WEBSOCKET"),

    ATOM("ATOM"),

    @JsonProperty("ATOMIX-MAP")
    ATOMIXMAP("ATOMIX-MAP"),

    @JsonProperty("ATOMIX-MESSAGING")
    ATOMIXMESSAGING("ATOMIX-MESSAGING"),

    @JsonProperty("ATOMIX-MULTIMAP")
    ATOMIXMULTIMAP("ATOMIX-MULTIMAP"),

    @JsonProperty("ATOMIX-QUEUE")
    ATOMIXQUEUE("ATOMIX-QUEUE"),

    @JsonProperty("ATOMIX-SET")
    ATOMIXSET("ATOMIX-SET"),

    @JsonProperty("ATOMIX-VALUE")
    ATOMIXVALUE("ATOMIX-VALUE"),

    ATLASMAP("ATLASMAP"),

    AVRO("AVRO"),

    @JsonProperty("AWS2-ATHENA")
    AWS2ATHENA("AWS2-ATHENA"),

    @JsonProperty("AWS2-CW")
    AWS2CW("AWS2-CW"),

    @JsonProperty("AWS2-DDB")
    AWS2DDB("AWS2-DDB"),

    @JsonProperty("AWS2-DDBSTREAM")
    AWS2DDBSTREAM("AWS2-DDBSTREAM"),

    @JsonProperty("AWS2-EC2")
    AWS2EC2("AWS2-EC2"),

    @JsonProperty("AWS2-ECS")
    AWS2ECS("AWS2-ECS"),

    @JsonProperty("AWS2-EKS")
    AWS2EKS("AWS2-EKS"),

    @JsonProperty("AWS2-EVENTBRIDGE")
    AWS2EVENTBRIDGE("AWS2-EVENTBRIDGE"),

    @JsonProperty("AWS2-IAM")
    AWS2IAM("AWS2-IAM"),

    @JsonProperty("AWS2-KMS")
    AWS2KMS("AWS2-KMS"),

    @JsonProperty("AWS2-KINESIS")
    AWS2KINESIS("AWS2-KINESIS"),

    @JsonProperty("AWS2-KINESIS-FIREHOSE")
    AWS2KINESISFIREHOSE("AWS2-KINESIS-FIREHOSE"),

    @JsonProperty("AWS2-LAMBDA")
    AWS2LAMBDA("AWS2-LAMBDA"),

    @JsonProperty("AWS2-MSK")
    AWS2MSK("AWS2-MSK"),

    @JsonProperty("AWS2-MQ")
    AWS2MQ("AWS2-MQ"),

    @JsonProperty("AWS2-S3")
    AWS2S3("AWS2-S3"),

    @JsonProperty("AWS-SECRETS-MANAGER")
    AWSSECRETSMANAGER("AWS-SECRETS-MANAGER"),

    @JsonProperty("AWS2-STS")
    AWS2STS("AWS2-STS"),

    @JsonProperty("AWS2-SNS")
    AWS2SNS("AWS2-SNS"),

    @JsonProperty("AWS2-SQS")
    AWS2SQS("AWS2-SQS"),

    @JsonProperty("AWS2-TRANSLATE")
    AWS2TRANSLATE("AWS2-TRANSLATE"),

    @JsonProperty("AZURE-EVENTHUBS")
    AZUREEVENTHUBS("AZURE-EVENTHUBS"),

    @JsonProperty("AZURE-COSMOSDB")
    AZURECOSMOSDB("AZURE-COSMOSDB"),

	@JsonProperty("AZURE-STORAGE-BLOB")
	AZURESTORAGEBLOB("AZURE-STORAGE-BLOB"),

    @JsonProperty("AZURE-STORAGE-DATALAKE")
    AZURESTORAGEDATALAKE("AZURE-STORAGE-DATALAKE"),

    @JsonProperty("AZURE-STORAGE-QUEUE")
	AZURESTORAGEQUEUE("AZURE-STORAGE-QUEUE"),

	@JsonProperty("BEAN-VALIDATOR")
	BEANVALIDATOR("BEAN-VALIDATOR"),

	BEAN("BEAN"),

	CLASS("CLASS"),

	BEANSTALK("BEANSTALK"),

	BONITA("BONITA"),

	BOX("BOX"),

	BRAINTREE("BRAINTREE"),

	BROWSE("BROWSE"),

	@JsonProperty("CAFFEINE-CACHE")
	CAFFEINECACHE("CAFFEINE-CACHE"),

	@JsonProperty("CAFFEINE-LOADCACHE")
	CAFFEINELOADCACHE("CAFFEINE-LOADCACHE"),

	CQL("CQL"),

	CHATSCRIPT("CHATSCRIPT"),

	CHUNK("CHUNK"),

	@JsonProperty("CM-SMS")
	CMSMS("CM-SMS"),

	CMIS("CMIS"),

	COAP("COAP"),

	COMETD("COMETD"),

	CONSUL("CONSUL"),

	CONTROLBUS("CONTROLBUS"),

	CORDA("CORDA"),

	COUCHBASE("COUCHBASE"),

	COUCHDB("COUCHDB"),

	CRON("CRON"),

	CRYPTO("CRYPTO"),

	@JsonProperty("CRYPTO-SMS")
	CRYPTOSMS("CRYPTO-SMS"),

	CXF("CXF"),

	CXFRS("CXFRS"),

	DATAFORMAT("DATAFORMAT"),

	DATASET("DATASET"),

	@JsonProperty("DATASET-TEST")
	DATASETTEST("DATASET-TEST"),

	@JsonProperty("DEBEZIUM-MONGODB")
	DEBEZIUMMONGODB("DEBEZIUM-MONGODB"),

	@JsonProperty("DEBEZIUM-MYSQL")
	DEBEZIUMMYSQL("DEBEZIUM-MYSQL"),

	@JsonProperty("DEBEZIUM-POSTGRESQL")
	DEBEZIUMPOSTGRESQL("DEBEZIUM-POSTGRESQL"),

	@JsonProperty("DEBEZIUM-SQLSERVER")
	DEBEZIUMSQLSERVER("DEBEZIUM-SQLSERVER"),

	DIGITALOCEAN("DIGITALOCEAN"),

	DIRECT("DIRECT"),

	@JsonProperty("DIRECT-VM")
	DIRECTVM("DIRECT-VM"),

	DISRUPTOR("DISRUPTOR"),

	@JsonProperty("DISRUPTOR-VM")
	DISRUPTORVM("DISRUPTOR-VM"),

    DJL("DJL"),

    DNS("DNS"),

	DOCKER("DOCKER"),

	DOZER("DOZER"),

	DRILL("DRILL"),

	DROPBOX("DROPBOX"),

	EHCACHE("EHCACHE"),

	ELASTICSEARCH("ELASTICSEARCH"),

	@JsonProperty("ELASTICSEARCH-REST")
	ELASTICSEARCHREST("ELASTICSEARCH-REST"),

	ELSQL("ELSQL"),

	ELYTRON("ELYTRON"),

	ETCD("ETCD"),

	EVENTADMIN("EVENTADMIN"),

	EXEC("EXEC"),

	FACEBOOK("FACEBOOK"),

	FHIR("FHIR"),

	FILE("FILE"),

	@JsonProperty("FILE-WATCH")
	FILEWATCH("FILE-WATCH"),

    FLATPACK("FLATPACK"),

    FLINK("FLINK"),

	FOP("FOP"),

	FREEMARKER("FREEMARKER"),

	FTP("FTP"),

	FTPS("FTPS"),

	GANGLIA("GANGLIA"),

	GEOCODER("GEOCODER"),

	GIT("GIT"),

	GITHUB("GITHUB"),

	@JsonProperty("GOOGLE-BIGQUERY")
	GOOGLEBIGQUERY("GOOGLE-BIGQUERY"),

	@JsonProperty("GOOGLE-BIGQUERY-SQL")
	GOOGLEBIGQUERYSQL("GOOGLE-BIGQUERY-SQL"),

	@JsonProperty("GOOGLE-CALENDAR")
	GOOGLECALENDAR("GOOGLE-CALENDAR"),

	@JsonProperty("GOOGLE-CALENDAR-STREAM")
	GOOGLECALENDARSTREAM("GOOGLE-CALENDAR-STREAM"),

	@JsonProperty("GOOGLE-DRIVE")
	GOOGLEDRIVE("GOOGLE-DRIVE"),

    @JsonProperty("GOOGLE-FUNCTIONS")
    GOOGLEFUNCTIONS("GOOGLE-FUNCTIONS"),

    @JsonProperty("GOOGLE-MAIL")
	GOOGLEMAIL("GOOGLE-MAIL"),

	@JsonProperty("GOOGLE-MAIL-STREAM")
	GOOGLEMAILSTREAM("GOOGLE-MAIL-STREAM"),

	@JsonProperty("GOOGLE-PUBSUB")
	GOOGLEPUBSUB("GOOGLE-PUBSUB"),

	@JsonProperty("GOOGLE-SHEETS")
	GOOGLESHEETS("GOOGLE-SHEETS"),

	@JsonProperty("GOOGLE-SHEETS-STREAM")
	GOOGLESHEETSSTREAM("GOOGLE-SHEETS-STREAM"),

    @JsonProperty("GOOGLE-STORAGE")
    GOOGLESTORAGE("GOOGLE-STORAGE"),

    GORA("GORA"),

	GRAPE("GRAPE"),

	GRAPHQL("GRAPHQL"),

	GRPC("GRPC"),

	@JsonProperty("GUAVA-EVENTBUS")
	GUAVAEVENTBUS("GUAVA-EVENTBUS"),

	@JsonProperty("HAZELCAST-ATOMICVALUE")
	HAZELCASTATOMICVALUE("HAZELCAST-ATOMICVALUE"),

	@JsonProperty("HAZELCAST-INSTANCE")
	HAZELCASTINSTANCE("HAZELCAST-INSTANCE"),

	@JsonProperty("HAZELCAST-LIST")
	HAZELCASTLIST("HAZELCAST-LIST"),

	@JsonProperty("HAZELCAST-MAP")
	HAZELCASTMAP("HAZELCAST-MAP"),

	@JsonProperty("HAZELCAST-MULTIMAP")
	HAZELCASTMULTIMAP("HAZELCAST-MULTIMAP"),

	@JsonProperty("HAZELCAST-QUEUE")
	HAZELCASTQUEUE("HAZELCAST-QUEUE"),

	@JsonProperty("HAZELCAST-REPLICATEDMAP")
	HAZELCASTREPLICATEDMAP("HAZELCAST-REPLICATEDMAP"),

	@JsonProperty("HAZELCAST-RINGBUFFER")
	HAZELCASTRINGBUFFER("HAZELCAST-RINGBUFFER"),

	@JsonProperty("HAZELCAST-SEDA")
	HAZELCASTSEDA("HAZELCAST-SEDA"),

	@JsonProperty("HAZELCAST-SET")
	HAZELCASTSET("HAZELCAST-SET"),

	@JsonProperty("HAZELCAST-TOPIC")
	HAZELCASTTOPIC("HAZELCAST-TOPIC"),

	HBASE("HBASE"),

	HDFS("HDFS"),

	HIPCHAT("HIPCHAT"),

	HTTP("HTTP"),

	HTTPS("HTTPS"),

    @JsonProperty("HWCLOUD-FUNCTIONGRAPH")
    HWCLOUDFUNCTIONGRAPH("HWCLOUD-FUNCTIONGRAPH"),

    @JsonProperty("HWCLOUD-IAM")
    HWCLOUDIAM("HWCLOUD-IAM"),

    @JsonProperty("HWCLOUD-SMN")
    HWCLOUDSMN("HWCLOUD-SMN"),

    IBMMQ("IBMMQ"),

	@JsonProperty("IEC60870-CLIENT")
	IEC60870CLIENT("IEC60870-CLIENT"),

	@JsonProperty("IEC60870-SERVER")
	IEC60870SERVER("IEC60870-SERVER"),

	@JsonProperty("IGNITE-CACHE")
	IGNITECACHE("IGNITE-CACHE"),

	@JsonProperty("IGNITE-COMPUTE")
	IGNITECOMPUTE("IGNITE-COMPUTE"),

	@JsonProperty("IGNITE-EVENTS")
	IGNITEEVENTS("IGNITE-EVENTS"),

	@JsonProperty("IGNITE-IDGEN")
	IGNITEIDGEN("IGNITE-IDGEN"),

	@JsonProperty("IGNITE-MESSAGING")
	IGNITEMESSAGING("IGNITE-MESSAGING"),

	@JsonProperty("IGNITE-QUEUE")
	IGNITEQUEUE("IGNITE-QUEUE"),

	@JsonProperty("IGNITE-SET")
	IGNITESET("IGNITE-SET"),

	IMAP("IMAP"),

	IMAPS("IMAPS"),

	INFINISPAN("INFINISPAN"),

	INFLUXDB("INFLUXDB"),

	IOTA("IOTA"),

	IPFS("IPFS"),

	IRC("IRC"),

	IRONMQ("IRONMQ"),

	JBPM("JBPM"),

	JCACHE("JCACHE"),

	JCLOUDS("JCLOUDS"),

	JCR("JCR"),

	JDBC("JDBC"),

	JETTY("JETTY"),

	JGROUPS("JGROUPS"),

	@JsonProperty("JGROUPS-RAFT")
	JGROUPSRAFT("JGROUPS-RAFT"),

	JING("JING"),

	JIRA("JIRA"),

	JMS("JMS"),

	JMX("JMX"),

	JOLT("JOLT"),

	JOOQ("JOOQ"),

	JPA("JPA"),

	JSLT("JSLT"),

	@JsonProperty("JSON-VALIDATOR")
	JSONVALIDATOR("JSON-VALIDATOR"),

    JSONATA("JSONATA"),

    JT400("JT400"),

    KAMELET("KAMELET"),

    KAFKA("KAFKA"),

	@JsonProperty("KUBERNETES-CONFIG-MAPS")
	KUBERNETESCONFIGMAPS("KUBERNETES-CONFIG-MAPS"),

	@JsonProperty("KUBERNETES-DEPLOYMENTS")
	KUBERNETESDEPLOYMENTS("KUBERNETES-DEPLOYMENTS"),

	@JsonProperty("KUBERNETES-HPA")
	KUBERNETESHPA("KUBERNETES-HPA"),

	@JsonProperty("KUBERNETES-JOB")
	KUBERNETESJOB("KUBERNETES-JOB"),

	@JsonProperty("KUBERNETES-NAMESPACES")
	KUBERNETESNAMESPACES("KUBERNETES-NAMESPACES"),

	@JsonProperty("KUBERNETES-NODES")
	KUBERNETESNODES("KUBERNETES-NODES"),

	@JsonProperty("KUBERNETES-PERSISTENT-VOLUMES")
	KUBERNETESPERSISTENTVOLUMES("KUBERNETES-PERSISTENT-VOLUMES"),

	@JsonProperty("KUBERNETES-PERSISTENT-VOLUMES-CLAIM")
	KUBERNETESPERSISTENTVOLUMESCLAIM("KUBERNETES-PERSISTENT-VOLUMES-CLAIM"),

	@JsonProperty("KUBERNETES-PODS")
	KUBERNETESPODS("KUBERNETES-PODS"),

	@JsonProperty("KUBERNETES-REPLICATION-CONTROLLERS")
	KUBERNETESREPLICATIONCONTROLLERS("KUBERNETES-REPLICATION-CONTROLLERS"),

	@JsonProperty("KUBERNETES-RESOURCES-QUOTA")
	KUBERNETESRESOURCESQUOTA("KUBERNETES-RESOURCES-QUOTA"),

	@JsonProperty("KUBERNETES-SECRETS")
	KUBERNETESSECRETS("KUBERNETES-SECRETS"),

	@JsonProperty("KUBERNETES-SERVICE-ACCOUNTS")
	KUBERNETESSERVICEACCOUNTS("KUBERNETES-SERVICE-ACCOUNTS"),

	@JsonProperty("KUBERNETES-SERVICES")
	KUBERNETESSERVICES("KUBERNETES-SERVICES"),

	@JsonProperty("OPENSHIFT-BUILDS")
	OPENSHIFTBUILDS("OPENSHIFT-BUILDS"),

	@JsonProperty("OPENSHIFT-BUILD-CONFIGS")
	OPENSHIFTBUILDCONFIGS("OPENSHIFT-BUILD-CONFIGS"),

	KUDU("KUDU"),

	LANGUAGE("LANGUAGE"),

	LDAP("LDAP"),

	LDIF("LDIF"),

	LEVELDB("LEVELDB"),

	LOG("LOG"),

	LUCENE("LUCENE"),

	LUMBERJACK("LUMBERJACK"),

	MASTER("MASTER"),

	MECTRICS("MECTRICS"),

	MICROMETER("MICROMETER"),

	@JsonProperty("MICROPROFILE-METRICS")
	MICROPROFILEMETRICS("MICROPROFILE-METRICS"),

    //OPC UA Server
	@JsonProperty("MILO-CLIENT")
	MILOCLIENT("MILO-CLIENT"),

	@JsonProperty("MILO-SERVER")
	MILOSERVER("MILO-SERVER"),

	MINA("MINA"),

    MINIO("MINIO"),

	MLLP("MLLP"),

	MOCK("MOCK"),

	MONGODB("MONGODB"),

	@JsonProperty("MONGODB-GRIDFS")
	MONGODBGRIDFS("MONGODB-GRIDFS"),

	MSV("MSV"),

	MUSTACHE("MUSTACHE"),

	MVEL("MVEL"),

	MYBATIS("MYBATIS"),

    @JsonProperty("MYBATIS-BEAN")
    MYBATISBEAN("MYBATIS-BEAN"),

    NAGIOS("NAGIOS"),

    NATS("NATS"),

    NETTY4("NETTY4"),

    @JsonProperty("NETTY-HTTP")
    NETTYHTTP("NETTY-HTTP"),

    NITRITE("NITRITE"),

	NSQ("NSQ"),

    @JsonProperty("OAI-PMH")
    OAIPMH("OAI-PMH"),

	OLINGO2("OLINGO2"),

	OLINGO4("OLINGO4"),

	@JsonProperty("OPENSTACK-CINDER")
	OPENSTACKCINDER("OPENSTACK-CINDER"),

	@JsonProperty("OPENSTACK-GLANCE")
	OPENSTACKGLANCE("OPENSTACK-GLANCE"),

	@JsonProperty("OPENSTACK-KEYSTONE")
	OPENSTACKKEYSTONE("OPENSTACK-KEYSTONE"),

	@JsonProperty("OPENSTACK-NEUTRON")
	OPENSTACKNEUTRON("OPENSTACK-NEUTRON"),

	@JsonProperty("OPENSTACK-")
	OPENSTACK("OPENSTACK-"),

	@JsonProperty("OPENSTACK-NOVA")
	OPENSTACKNOVA("OPENSTACK-NOVA"),

	@JsonProperty("OPENSTACK-SWIFT")
	OPENSTACKSWIFT("OPENSTACK-SWIFT"),

	OPTAPLANNER("OPTAPLANER"),

	PAHO("PAHO"),

    @JsonProperty("PAHO-MQTT")
    PAHOMQTT("PAHO-MQTT"),

	PAXLOGGING("PAXLOGGING"),

	PDF("PDF"),

	@JsonProperty("PG-REPLICATION-SLOT")
	PGREPLICATIONSLOT("PG-REPLICATION-SLOT"),

	PGEVENT("PGEVENT"),

	@JsonProperty("PLATFORM-HTTP")
	PLATFORMHTTP("PLATFORM-HTTP"),

	LPR("LPR"),

	PUBNUB("PUBNUB"),

	PULSAR("PULSAR"),

	QUARTZ("QUARTZ"),

	QUICKFIX("QUICKFIX"),

	RABBITMQ("RABBITMQ"),

	@JsonProperty("REACTIVE-STREAMS")
	REACTIVESTREAMS("REACTIVE-STREAMS"),

	REF("REF"),

	REST("REST"),

    RESTLET("RESTLET"),

	@JsonProperty("REST-API")
	RESTAPI("REST-API"),

    RESTEASY("RESTEASY"),

    @JsonProperty("REST-OPENAPI")
	RESTOPENAPI("REST-OPENAPI"),

	@JsonProperty("REST-SWAGGER")
	RESTSWAGGER("REST-SWAGGER"),

	RSS("RSS"),

	SAGA("SAGA"),

	SALESFORCE("SALESFORCE"),

	@JsonProperty("SAP-NETWEAVER")
	SAPNETWEAVER("SAP-NETWEAVER"),

	SCHEDULER("SCHEDULER"),

	SCHEMATRON("SCHEMATRON"),

	SCP("SCP"),

	SEDA("SEDA"),

	SERVICE("SERVICE"),

	SERVICENOW("SERVICENOW"),

	SERVLET("SERVLET"),

	SFTP("SFTP"),

	SIP("SIP"),

	SIPS("SIPS"),

	SJMS("SJMS"),

	SJMS2("SJMS2"),

	SLACK("SLACK"),

	SMMP("SMMP"),

	SMMPS("SMMPS"),

	SNMP("SNMP"),

	SMTP("SMTP"),

	SMTPS("SMTPS"),

	SOLR("SOLR"),

	SOLRS("SOLRS"),

	SPARK("SPARK"),

	@JsonProperty("SPARK-REST")
	SPARKREST("SPARK-REST"),

	SPLUNK("SPLUNK"),

    @JsonProperty("SPLUNK-HEC")
    SPLUNKHEC("SPLUNK-HEC"),

	@JsonProperty("SPRING-BATCH")
	SPRINGBATCH("SPRING-BATCH"),

    @JsonProperty("SPRING-JDBC")
    SPRINGJDBC("SPRING-JDBC"),

    @JsonProperty("SPRING-INTEGRATION")
	SPRINGINTEGRATION("SPRING-INTEGRATION"),

	@JsonProperty("SPRING-LDAP")
	SPRINGLDAP("SPRING-LDAP"),

    @JsonProperty("SPRING-RABBITMQ")
    SPRINGRABBITMQ("SPRING-RABBITMQ"),

    @JsonProperty("SPRING-REDIS")
	SPRINGREDIS("SPRING-REDIS"),

	@JsonProperty("SPRING-WS")
	SPRINGWS("SPRING-WS"),

	@JsonProperty("SPRING-EVENT")
	SPRINGEVENT("SPRING-EVENT"),

	SQL("SQL"),

	@JsonProperty("SQL-STORED")
	SQLSTORED("SQL-STORED"),

	SSH("SSH"),

	SONICMQ("SONICMQ"),

	STAX("STAX"),

    STICH("STICH"),

	STOMP("STOMP"),

	STREAM("STREAM"),

	STUB("STUB"),

	TELEGRAM("TELEGRAM"),

	THRIFT("THRIFT"),

	TIKA("TIKA"),

	TIMER("TIMER"),

	TWILIO("TWILIO"),

	@JsonProperty("TWITTER-DIRECTMESSAGE")
	TWITTERDIRECTMESSAGE("TWITTER-DIRECTMESSAGE"),

	@JsonProperty("TWITTER-SEARCH")
	TWITTERSEARCH("TWITTER-SEARCH"),

	@JsonProperty("TWITTER-TIMELINE")
	TWITTERTIMELINE("TWITTER-TIMELINE"),

	UNDERTOW("UNDERTOW"),

	VALIDATOR("VALIDATOR"),

	VELOCITY("VELOCITY"),

	VERTX("VERTX"),

    @JsonProperty("VERTX-HTTP")
    VERTXHTTP("VERTX-HTTP"),

    @JsonProperty("VERTX-KAFKA")
    VERTXKAFKA("VERTX-KAFKA"),

    @JsonProperty("VERTX-WEBSOCKET")
    VERTXWEBSOCKET("VERTX-WEBSOCKET"),

    VM("VM"),

	WASTEBIN("WASTEBIN"),

	WEATHER("WEATHER"),

	WEB3J("WEB3J"),

	WEBHOOK("WEBHOOK"),

	WEBSOCKET("WEBSOCKET"),

	@JsonProperty("WEBSOCKET-JSR")
	WEBSOCKETJSR("WEBSOCKET-JSR"),

	WORDPRESS("WORDPRESS"),

	XCHANGE("XCHANGE"),

	XJ("XJ"),

	XMPP("XMPP"),

	XQUERY("XQUERY"),

	XSLT("XSLT"),

	@JsonProperty("XSLT-SAXON")
	XSLTSAXON("XSLT-SAXON"),

	YAMMER("YAMMER"),

	ZENDESK("ZENDESK"),

	ZOOKEEPER("ZOOKEEPER"),

	@JsonProperty("ZOOKEEPER-MASTER")
	ZOOKEEPERMASTER("ZOOKEEPER-MASTER");


    private String endpoint;

    ComponentType(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getEndpoint() {
        return endpoint;
    }


}
