mode: auto

silent: false

commentMessage: 'Branch ${branchName} created for issue: ${issue.number}-${issue.title}'

defaultBranch: 'develop'

branchName: 'issue-${issue.number}/${issue.title,}'

gitSafeReplacementChar: '-'

branches:
  - label: [ feature ]
    prefix: feature/

  - label: [ bug ]
    prefix: bugfix/

  - label: [ documentation ]
    prefix: documentation/

  - label: '*'
    prefix: issues/

  - label: no-branch
    skip: true

autoCloseIssue: true
openPR: true

copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: false
copyIssueMilestoneToPR: false
