name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    collapse-after: 10
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    collapse-after: 10
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

exclude-labels:
  - 'skip-release'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Download links

  - [Jar files](https://github.com/orgs/assimbly/packages?repo_name=gateway)
  - [Docker images](https://hub.docker.com/u/assimbly)
