name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to operatie on'
        default: 'develop'
        type: string    
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true
      tag:
        description: 'Tag to use for this release'
        default: 'development'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to operatie on'
        default: 'develop'
        type: string        
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true
      tag:
        description: 'Tag to use for this release'
        type: string

jobs:

  test-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable if not empty
        if: "${{ inputs.tag != '' }}"
        run: echo Creating release for milestone ${{ inputs.tag }}         
      - name: Print message if empty
        if: "${{ inputs.tag == '' }}"        
        run: echo Tag value is empty

  test-milestone:
    needs: test-tag
    runs-on: ubuntu-latest
    steps:
      - name: Print variable if not empty
        if: "${{ inputs.milestone != '' }}"
        run: |
          echo Creating release for milestone ${{ inputs.milestone }}
          exit 1
      - name: Print message if empty
        if: "${{ inputs.milestone == '' }}"
        run: echo Milestone value is empty

  test-branch:
    needs: test-milestone
    runs-on: ubuntu-latest
    steps:
      - name: Print variable if not empty
        if: "${{ inputs.branch != '' }}"
        run: |
          echo Creating release for milestone ${{ inputs.branch }}
          exit 1
      - name: Print message if empty
        if: "${{ inputs.branch == '' }}"
        run: echo Milestone value is empty
