name: Release

on:
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true
      tag:
        description: 'Tag to use for this release'
        default: 'develop'
        type: string

  workflow_call:
    inputs:
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true
      tag:
        description: 'Tag to use for this release'
        default: 'develop'
        type: string

jobs:
  delete_old_snapshots:

    runs-on: ubuntu-latest

    env:
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          organization: assimbly
          type: maven
          keep: 0
          semver-pattern: "${{inputs.milestone}}"
          names: |
            org.assimbly.gateway.full
            org.assimbly.gateway.headless
            org.assimbly.gateway.integration
            org.assimbly.gateway.broker

  call-full-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'full'
      branch: ${{ github.ref_name }}

  call-integration-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'integration'
      branch: ${{ github.ref_name }}

  call-broker-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'broker'
      branch: ${{ github.ref_name }}

  call-headless-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'headless'
      branch: ${{ github.ref_name }}

  call-full-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'full'
      branch: ${{ github.ref_name }}
      tag: "${{inputs.tag}}"
      type: 'full'

  call-integration-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'integration'
      branch: ${{ github.ref_name }}
      tag: "${{inputs.tag}}"
      type: 'default'

  call-broker-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'broker'
      branch: ${{ github.ref_name }}
      tag: "${{inputs.tag}}"
      type: 'default'

  call-headless-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'headless'
      branch: ${{ github.ref_name }}
      tag: "${{inputs.tag}}"
      type: 'full'

  call-headless-release-aws-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-aws-images.yml
    secrets: inherit
    with:
      module: 'headless'
      branch: ${{ github.ref_name }}
      tag: "${{inputs.tag}}"
      type: 'full'

  call-broker-release-aws-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-aws-images.yml
    secrets: inherit
    with:
      module: 'broker'
      branch: ${{ github.ref_name }}
      tag: "${{inputs.tag}}"
      type: 'default'


