name: Start Release

on:
  workflow_dispatch:
  issues:
    types: [ opened, reopened, edited ]

jobs:

  release-new-version:

    if: |
      (contains(github.event.issue.labels.*.name, 'major') ||
      contains(github.event.issue.labels.*.name, 'minor') ||
      contains(github.event.issue.labels.*.name, 'patch')) &&
      github.event.issue.milestone.title != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Start release
        run: echo "Start release of gateway"

  call-base-release-version:
    needs: release-new-version
    uses: assimbly/base/.github/workflows/release-start.yml@develop
    with:
      branch: 'develop'
      repository: assimbly/base
      milestone: "${{github.event.issue.milestone.title}}-SNAPSHOT"
