name: Start Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  call-gateway-update-version:
    needs: release-new-version
    uses: ./.github/workflows/update-version.yml
    secrets: inherit
    with:
      branch: 'develop'
      milestone: "${{github.event.issue.milestone.title}}-SNAPSHOT"

  call-base-release-version:
    needs: release-new-version
    uses: assimbly/base/.github/workflows/update-version.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
      milestone: "${{github.event.issue.milestone.title}}-SNAPSHOT"

  call-runtime-release-version:
    needs: release-new-version
    uses: assimbly/runtime/.github/workflows/update-version.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
      milestone: "${{github.event.issue.milestone.title}}-SNAPSHOT"

  call-custom-components-release-version:
    needs: release-new-version
    uses: assimbly/custom-components/.github/workflows/update-version.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
      milestone: "${{github.event.issue.milestone.title}}-SNAPSHOT"
