name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to operatie on'
        default: 'develop'
        type: string    
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true
      tag:
        description: 'Tag to use for this release'
        default: 'development'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to operatie on'
        default: 'develop'
        type: string        
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true
      tag:
        description: 'Tag to use for this release'
        type: string

jobs:

  test-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable if not empty
        if: "${{ github.event.inputs.milestone != '' }}"
        run: echo Creating release for milestone ${{ github.event.inputs.milestone }}
      - name: Print message if empty
        if: "${{ github.event.inputs.milestone == '' }}"

  test-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable if not empty
        if: "${{ github.event.inputs.tag != '' }}"
        run: echo Creating release for milestone ${{ github.event.inputs.tag }}
      - name: Print message if empty
        if: "${{ github.event.inputs.tag == '' }}"        
        run: echo Milestone value is empty
