name: Release for all repositories
# Run this task when the snapshots are merged into main

on:
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

  workflow_call:
    inputs:
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

jobs:
  call-base-release:
    uses: assimbly/base/.github/workflows/release.yml@main
    secrets: inherit
    with:
      branch: 'main'
      milestone: ${{ inputs.milestone }}

  call-custom-components-release:
    uses: assimbly/custom-components/.github/workflows/release.yml@main
    needs: call-base-release
    secrets: inherit
    with:
      branch: 'main'
      milestone: ${{ inputs.milestone }}

  call-runtime-release:
    uses: assimbly/custom-components/.github/workflows/release.yml@main
    needs: call-custom-components-release
    secrets: inherit
    with:
      branch: 'main'
      milestone: ${{ inputs.milestone }}

  call-gateway-release:
    uses: ./.github/workflows/release.yml
    needs: call-runtime-release
    secrets: inherit
    with:
      branch: 'main'
      milestone: ${{ inputs.milestone }}
      tag: ${{inputs.milestone}}

  call-release-notes-drafter:
    needs: call-gateway-release
    uses: ./.github/workflows/release-drafter.yml
    secrets: inherit
    with:
      branch: 'main'
      milestone: ${{ inputs.milestone }}
