name: Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Start release
        run: echo "Start release of gateway"

  call-base-release:
    uses: assimbly/base/.github/workflows/release.yml@develop
    secrets: inherit
    with:
      branch: 'develop'

  call-runtime-release:
    needs: call-base-release
    uses: assimbly/runtime/.github/workflows/release.yml@develop
    secrets: inherit
    with:
      branch: 'develop'

  call-custom-components-release:
    needs: call-base-release
    uses: assimbly/custom-components/.github/workflows/release.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
