name: Finish Release

on:
  workflow_dispatch:
  issues:
    types: [ closed ]

jobs:

  release:

    if: |
      (contains(github.event.issue.labels.*.name, 'major') ||
      contains(github.event.issue.labels.*.name, 'minor') ||
      contains(github.event.issue.labels.*.name, 'patch')) &&
      github.event.issue.milestone.title != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Start release
        run: echo "Start release of gateway"

  call-base-release:
    needs: release
    uses: assimbly/base/.github/workflows/release-start.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
      milestone: '${github.event.issue.milestone.title}'

  call-runtime-release:
    needs: call-base-release
    uses: assimbly/runtime/.github/workflows/release-start.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
      milestone: '${github.event.issue.milestone.title}'

  call-custom-components-release:
    needs: call-base-release
    uses: assimbly/custom-components/.github/workflows/release-start.yml@develop
    secrets: inherit
    with:
      branch: 'develop'
      milestone: '${github.event.issue.milestone.title}'
