name: Release Snapshots

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * *'

jobs:
  delete_old_snapshots:

    runs-on: ubuntu-latest

    env:
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.gateway.full
            org.assimbly.gateway.headless
            org.assimbly.gateway.integration
            org.assimbly.gateway.broker

  call-full-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'full'
      branch: 'develop'

  call-integration-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'integration'
      branch: 'develop'

  call-broker-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'broker'
      branch: 'develop'

  call-headless-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      module: 'headless'
      branch: 'develop'

  call-full-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'full'
      branch: 'develop'
      tag: 'develop'
      type: 'full'

  call-integration-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'integration'
      branch: 'develop'
      tag: 'develop'
      type: 'default'

  call-broker-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'broker'
      branch: 'develop'
      tag: 'develop'
      type: 'default'

  call-headless-release-dockerhub-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-dockerhub-images.yml
    secrets: inherit
    with:
      module: 'headless'
      branch: 'develop'
      tag: 'develop'
      type: 'full'

  call-headless-release-aws-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-aws-images.yml
    secrets: inherit
    with:
      module: 'headless'
      branch: 'develop'
      tag: 'development'
      type: 'full'

  call-broker-release-aws-image:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-aws-images.yml
    secrets: inherit
    with:
      module: 'broker'
      branch: 'develop'
      tag: 'development'
      type: 'default'

