name: Finish Release

on:
  workflow_dispatch:
  issues:
    types: [ closed ]

jobs:

  release-new-version:

    if: |
      (contains(github.event.issue.labels.*.name, 'major') ||
      contains(github.event.issue.labels.*.name, 'minor') ||
      contains(github.event.issue.labels.*.name, 'patch')) &&
      github.event.issue.milestone.title != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

      - name: Finish release
        run: echo "Start release of gateway"

  call-gateway-update-version:
    needs: release-new-version
    uses: ./.github/workflows/update-version.yml
    secrets: inherit
    with:
      branch: "${{github.event.issue.milestone.title}}"
      milestone: "${{github.event.issue.milestone.title}}"
