name: Release Drafter

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'main'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft a Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
