name: Start New Release (update versions for all repositories)

on:
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

  workflow_call:
    inputs:
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

jobs:
  call-gateway-update-version:
    uses: ./.github/workflows/update-version.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      milestone: "${{inputs.milestone}}-SNAPSHOT"

  call-base-release-version:
    uses: assimbly/base/.github/workflows/update-version.yml@develop
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      milestone: "${{inputs.milestone}}-SNAPSHOT"

  call-custom-components-release-version:
    uses: assimbly/custom-components/.github/workflows/update-version.yml@develop
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      milestone: "${{inputs.milestone}}-SNAPSHOT"

  call-runtime-release-version:
    uses: assimbly/runtime/.github/workflows/update-version.yml@develop
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
      milestone: "${{inputs.milestone}}-SNAPSHOT"

