name: Update Version Number

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: assimbly/gateway
        ref: ${{ inputs.branch }}

    - name: Update Gradle Version
      run: |
        echo "Updating to version: ${{inputs.milestone}}"
        ./gradlew -q version -PnewVersion=${{inputs.milestone}} --settings-file ./settings.gradle

    - name: Diff check
      run: git diff

    - name: Add & Commit
      if: ${{inputs.new_branch}} == ''
      uses: EndBug/add-and-commit@v9.1.3
      with:
        add: '.'
        default_author: github_actions
        message: 'update version to ${{inputs.milestone}}'
        push: true
