name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '!workflows'
      - master

jobs:
  update_version:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3

    - name: Update Gradle Version
      run: |
        echo "Updating to version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
        ./gradlew -q version -PnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH) --settings-file ./settings.gradle

    - name: Diff check
      run: git diff

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: '.'
        default_author: github_actions
        push: origin HEAD:develop --force
