name: Update Version Number

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        type: string
        default: 'develop'    
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

  workflow_call: 
    inputs:
      branch:
        description: 'Branch to use'
        type: string
        default: 'develop'    
      milestone:
        description: 'Milestone to use as version'
        type: string
        required: true

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ inputs.branch }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Update Gradle Version
      run: |
        echo "Updating to version: ${{inputs.milestone}}"
        ./gradlew -q version -PnewVersion=${{inputs.milestone}} --settings-file ./settings.gradle

    - name: Diff check
      run: git diff

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        add: '.'
        default_author: github_actions
        message: 'update version to ${{inputs.milestone}}'
        push: true
